Resources:
  GeoAlertLambdaServiceRoleC87EC0B6:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertLambda/ServiceRole/Resource
  GeoAlertLambdaA18E85DD:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 3cc4b02fe5d990f57230320d82b92cec1af76e81c4c369c0476f83f10f589feb.zip
      Handler: GeoAlert.Api::GeoAlert.Api.LambdaEntryPoint::FunctionHandlerAsync
      MemorySize: 256
      Role:
        Fn::GetAtt:
          - GeoAlertLambdaServiceRoleC87EC0B6
          - Arn
      Runtime: dotnet8
      Timeout: 10
    DependsOn:
      - GeoAlertLambdaServiceRoleC87EC0B6
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertLambda/Resource
      aws:asset:path: asset.3cc4b02fe5d990f57230320d82b92cec1af76e81c4c369c0476f83f10f589feb
      aws:asset:is-bundled: false
      aws:asset:property: Code
  GeoAlertLambdaLogGroup9E45BEAA:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - /aws/lambda/
            - Ref: GeoAlertLambdaA18E85DD
      RetentionInDays: 731
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertLambda/LogGroup/Resource
  GeoAlertApi1FB193D0:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: GeoAlertApi
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Resource
  GeoAlertApiDeployment29081BF030467eaac3645f6061ccfc167dad0e7c:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: GeoAlertApi1FB193D0
    DependsOn:
      - GeoAlertApiproxyANY6BBB10FE
      - GeoAlertApiproxy45A2E714
      - GeoAlertApiANY30B46FC5
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Deployment/Resource
      aws:cdk:do-not-refactor: true
  GeoAlertApiDeploymentStageprod63BD4010:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: GeoAlertApiDeployment29081BF030467eaac3645f6061ccfc167dad0e7c
      RestApiId:
        Ref: GeoAlertApi1FB193D0
      StageName: prod
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/DeploymentStage.prod/Resource
  GeoAlertApiproxy45A2E714:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - GeoAlertApi1FB193D0
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: GeoAlertApi1FB193D0
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/{proxy+}/Resource
  GeoAlertApiproxyANYApiPermissionGeoAlertInfraStackGeoAlertApiD51E6610ANYproxyC0D449E1:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GeoAlertLambdaA18E85DD
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GeoAlertApi1FB193D0
            - /
            - Ref: GeoAlertApiDeploymentStageprod63BD4010
            - /*/*
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/{proxy+}/ANY/ApiPermission.GeoAlertInfraStackGeoAlertApiD51E6610.ANY..{proxy+}
  GeoAlertApiproxyANYApiPermissionTestGeoAlertInfraStackGeoAlertApiD51E6610ANYproxy6ACC38E5:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GeoAlertLambdaA18E85DD
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GeoAlertApi1FB193D0
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/{proxy+}/ANY/ApiPermission.Test.GeoAlertInfraStackGeoAlertApiD51E6610.ANY..{proxy+}
  GeoAlertApiproxyANY6BBB10FE:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - GeoAlertLambdaA18E85DD
                  - Arn
              - /invocations
      ResourceId:
        Ref: GeoAlertApiproxy45A2E714
      RestApiId:
        Ref: GeoAlertApi1FB193D0
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/{proxy+}/ANY/Resource
  GeoAlertApiANYApiPermissionGeoAlertInfraStackGeoAlertApiD51E6610ANYA07C89DD:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GeoAlertLambdaA18E85DD
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GeoAlertApi1FB193D0
            - /
            - Ref: GeoAlertApiDeploymentStageprod63BD4010
            - /*/
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/ANY/ApiPermission.GeoAlertInfraStackGeoAlertApiD51E6610.ANY..
  GeoAlertApiANYApiPermissionTestGeoAlertInfraStackGeoAlertApiD51E6610ANYBCDD05AE:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - GeoAlertLambdaA18E85DD
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: GeoAlertApi1FB193D0
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/ANY/ApiPermission.Test.GeoAlertInfraStackGeoAlertApiD51E6610.ANY..
  GeoAlertApiANY30B46FC5:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - GeoAlertLambdaA18E85DD
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - GeoAlertApi1FB193D0
          - RootResourceId
      RestApiId:
        Ref: GeoAlertApi1FB193D0
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertApi/Default/ANY/Resource
  GeoFencesTable0E8059F4:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoFencesTable/Resource
  GeoAlertNotificationsTopic35BD8442:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: GeoAlert Notifications Topic
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertNotificationsTopic/Resource
  GeoAlertEventRule09BA31E8:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - geoalert.app
        detail-type:
          - GeoAlertEvent
      State: ENABLED
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/GeoAlertEventRule/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/6VU32/TMBD+W8gj8sIoPO2tg4ImGCtteUBVVV3tW+bNsS3b2QhR/ved7aTthhCaeIp9P7777vNdJuXkdFKevoIHf8LF3YmSu7JbBuB3jEzbTkG9E1B2nxrNgzR63RWu0UHWWJwVrwtW3IAWCt1w40aMjhpr49ql/D0aYpJpQrr1G/bhWo+g8TxHV0vv6dYzCXXZLYxCqgbeNzWK87Y46wrrpObSgppybojGgJxjYsI04eUSRAE0VCjmRkku0RdnhHdsa6duiN1kQhGiZ/7dlhAx+HIaP3Qvzxt+h+EcPK43TJnKl91XU312prGEqYbjNxhkyWhjRM/AygoCPkBLeUnRBfowtZKSBV5Do8KFDlg52NN/rqx15hdpEFyDrHA5+1CPdS8Kz81mK/uIVpm2Rh0SG8+dtEc0iPtwchhA6kO439cGIVaG2pUc1IWIOpOiL7UnUgd0RlNYYaI0mo7IJyejFkzjOKaHId+GzWPfo5mSLTjcz8lfpR4clxhujLhK3R+aO4IYuOc4oh1L7sVMJVn2xTUZLONrhmDHvGSQf7Awzwr/J0LilRN6JloNtRG03CvYqUGZIGP4F0y7pWG/06G18biMO7STSkldXebFnk9/buezxXYx+/5jtlyloajNPai8TxRBAxScaYfyqRhtlKaFWRkreXxP6a2C9tk0Jm/P8D4OFm1/k0im6xxCwLipXfFEEBHnUa0yWcIZXmf2JGf9j6Tx/ageAewnJ8XGgUq/gDhtJEIMvGqCbULPNAlS3vo395P35Vv6gd56KU+GX2O5yN9HwjMRTV0FAAA=
    Metadata:
      aws:cdk:path: GeoAlertInfraStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  GeoAlertApiEndpoint8A7B6DD7:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: GeoAlertApi1FB193D0
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: GeoAlertApiDeploymentStageprod63BD4010
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

